---
- name: Hello world!
  hosts: tag_AWXA_True
  vars:
    # ansible_connection: community.aws.aws_ssm
    # ansible_aws_ssm_region: eu-central-1
    # ansible_aws_ssm_plugin: /runner/requirements_collections/session-manager-plugin #Failed to find the executable specified /usr/local/bin/session-manager-plugin. Please verify if the executable exists and re-try
  tasks:
    - name: download aws cli
      ansible.builtin.get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /home/ec2-user/awscliv2.zip

    - name: Install unzip
      ansible.builtin.package:
        name: unzip
        state: present

    - name: unzip aws cli
      ansible.builtin.unarchive:
        src: /home/ec2-user/awscliv2.zip
        dest: /home/ec2-user/
        remote_src: yes
    
    - name: install install aws cli
      ansible.builtin.shell: /home/ec2-user/./aws/install --update
    
    - name: download installation scripts
      ansible.builtin.shell: /usr/local/bin/aws s3 cp "s3://cadit-pipelines-collaudo/demo_do_not_delete/jboss.sh" /tmp --region eu-south-1

    - name: install Jboss
      ansible.builtin.shell: ./tmp/jboss.sh

    # - name: Put helloworld file
    #   ansible.builtin.file:
    #     path: "/home/ec2-user/hello_world_A.txt"
    #     state: touch

    # - name: Add line to helloworld
    #   lineinfile:
    #     path: /home/ec2-user/hello_world_A.txt
    #     line: 'AWX tower calls AWS, AWS please answer'
