---
- name: Hello world!
  hosts: tag_AWXA_True
  vars:
    # ansible_connection: community.aws.aws_ssm
    # ansible_aws_ssm_region: eu-central-1
    # ansible_aws_ssm_plugin: /runner/requirements_collections/session-manager-plugin #Failed to find the executable specified /usr/local/bin/session-manager-plugin. Please verify if the executable exists and re-try
  tasks:
    - name: download aws cli
      ansible.builtin.get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /home/ec2-user/awscliv2.zip

    - name: unzip aws cli
      ansible.builtin.unarchive:
        src: /home/ec2-user/awscliv2.zip
        dest: .
    
    - name: install install aws cli
      ansible.builtin.shell: /home/ec2-user/./aws/install
    


    - name: install Jboss
      ansible.builtin.shell: ls && pwd

    # - name: Put helloworld file
    #   ansible.builtin.file:
    #     path: "/home/ec2-user/hello_world_A.txt"
    #     state: touch

    # - name: Add line to helloworld
    #   lineinfile:
    #     path: /home/ec2-user/hello_world_A.txt
    #     line: 'AWX tower calls AWS, AWS please answer'
